#!/usr/bin/env node
/**
 * oh-my-openclaw interactive setup wizard
 *
 * Pulls the two reference images, installs @goplus/agentguard,
 * validates built-in skills, then writes a ready-to-use
 * docker-compose override for the user's environment.
 *
 * Run: node scripts/setup.js
 */

import { execSync, spawnSync } from 'child_process';
import { writeFileSync, existsSync } from 'fs';
import { createInterface } from 'readline/promises';
import { resolve } from 'path';

const ROOT = new URL('..', import.meta.url).pathname;

const IMAGES = [
  'alpine/openclaw:latest',
  'ghcr.io/openclaw/openclaw',
];

// ── Helpers ──────────────────────────────────────────────────────────────────
function run(cmd, desc) {
  console.log(`\n[setup] ${desc}...`);
  const result = spawnSync(cmd, { shell: true, stdio: 'inherit' });
  if (result.status !== 0) {
    console.error(`[setup] FAILED: ${cmd}`);
    process.exit(1);
  }
}

function checkDocker() {
  const r = spawnSync('docker', ['info'], { stdio: 'pipe' });
  if (r.status !== 0) {
    console.error('[setup] Docker is not running or not installed.');
    console.error('        Please start Docker and re-run setup.');
    process.exit(1);
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────
const rl = createInterface({ input: process.stdin, output: process.stdout });

console.log('');
console.log('  oh-my-openclaw — setup wizard');
console.log('  ================================');
console.log('  Claude Code level experience for OpenClaw');
console.log('');

// Step 1: Verify Docker
checkDocker();

// Step 2: Pull reference images for validation
console.log('[setup] Pulling OpenClaw reference images...');
for (const img of IMAGES) {
  run(`docker pull ${img}`, `Pulling ${img}`);
}

// Step 3: npm install (gets @goplus/agentguard)
run(`npm install --prefix ${ROOT}`, 'Installing npm dependencies (@goplus/agentguard and others)');

// Step 4: Validate built-in skills through AgentGuard
run(`node ${ROOT}/scripts/validate.js --all --strict`, 'Validating built-in skills with AgentGuard');

// Step 5: Ask user for workspace path
const workspace = await rl.question('\n[setup] Workspace path to mount [default: $PWD]: ');
const port = await rl.question('[setup] Gateway port [default: 18789]: ');
const mode = await rl.question('[setup] Default agent mode (team/autopilot) [default: team]: ');
const image = await rl.question('[setup] Base image (full/alpine) [default: alpine]: ');
rl.close();

const wsPath  = workspace.trim() || '${PWD}';
const gwPort  = port.trim() || '18789';
const agMode  = mode.trim() || 'team';
const imgTag  = image.trim() === 'full' ? 'full' : 'alpine';

// Step 6: Write docker-compose.override.yml
const overridePath = resolve(ROOT, 'docker', 'docker-compose.override.yml');
const override = `# Auto-generated by oh-my-openclaw setup — do not edit manually
# Re-run: node scripts/setup.js
services:
  openclaw-${imgTag}:
    environment:
      - OPENCLAW_GATEWAY_PORT=${gwPort}
      - OMOCW_AGENT_MODE=${agMode}
    volumes:
      - ${wsPath}:/workspace
`;

writeFileSync(overridePath, override);
console.log(`\n[setup] Written: ${overridePath}`);

// Step 7: Done
console.log(`
[setup] Setup complete!

To start oh-my-openclaw (${imgTag} image):

  cd ${ROOT}/docker
  docker compose --profile ${imgTag} up --build

To validate custom skills before adding them:

  docker compose --profile validate up \\
    -e SKILLS_DIR=/path/to/your/skills

Host openclaw is untouched. All activity runs inside Docker.
`);
